// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyG33rp5ZwDyARJQ30pK2gDIYkstZ4efA',
    appId: '1:786940598098:web:f05d49169d949c9f51cc8b',
    messagingSenderId: '786940598098',
    projectId: 'cashier-app-a9033',
    authDomain: 'cashier-app-a9033.firebaseapp.com',
    storageBucket: 'cashier-app-a9033.appspot.com',
    measurementId: 'G-42TM674S2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFRyA5iPmOspILP6IV5XhPjEbH2L46RdQ',
    appId: '1:786940598098:android:cd11ba1e7d822db351cc8b',
    messagingSenderId: '786940598098',
    projectId: 'cashier-app-a9033',
    storageBucket: 'cashier-app-a9033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-aJaCbChzlKXwv18u1SnjXSwNCxppMI',
    appId: '1:786940598098:ios:1e4c777f9704a9e051cc8b',
    messagingSenderId: '786940598098',
    projectId: 'cashier-app-a9033',
    storageBucket: 'cashier-app-a9033.appspot.com',
    androidClientId: '786940598098-14ie9e4fopuqhhpapv1lnrhdf2v1hc78.apps.googleusercontent.com',
    iosClientId: '786940598098-h293doarpa642hr3n8t4op1vo41skofc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ-aJaCbChzlKXwv18u1SnjXSwNCxppMI',
    appId: '1:786940598098:ios:1e4c777f9704a9e051cc8b',
    messagingSenderId: '786940598098',
    projectId: 'cashier-app-a9033',
    storageBucket: 'cashier-app-a9033.appspot.com',
    androidClientId: '786940598098-14ie9e4fopuqhhpapv1lnrhdf2v1hc78.apps.googleusercontent.com',
    iosClientId: '786940598098-h293doarpa642hr3n8t4op1vo41skofc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashierApp',
  );
}
